# Generated by Django 4.1 on 2022-10-30 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128, verbose_name='Unique SHA256 hash')),
                ('provider_identity', models.CharField(choices=[('local', 'local')], max_length=64, verbose_name='Provider Identity')),
                ('path', models.CharField(max_length=10240, verbose_name='Locale the file in the provider')),
                ('download_count', models.IntegerField(verbose_name='Download Counts')),
                ('time', models.DateTimeField(verbose_name='Time File Created')),
                ('size', models.IntegerField(blank=True, verbose_name='Size of the file, by KiB')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Display Name')),
                ('description', models.TextField(blank=True)),
                ('time', models.DateTimeField(blank=True, verbose_name='Time Entity Created.')),
                ('file_type', models.IntegerField()),
                ('download_count', models.IntegerField()),
                ('is_need_review', models.BooleanField(verbose_name='Whether need to be reviewed, which is by user upload.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_disk.file')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='share_disk.entity')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_disk.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
