# Generated by Django 4.1 on 2022-10-30 14:30

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('share_disk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='download_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='share_disk.file'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
