# Generated by Django 3.2.7 on 2021-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='File name')),
                ('hash', models.CharField(max_length=100, verbose_name='MD5')),
                ('path', models.TextField(max_length=1024, verbose_name='full path of file')),
                ('user_id', models.IntegerField()),
                ('size', models.IntegerField(verbose_name='Size By KiB')),
                ('time', models.DateTimeField(verbose_name='Upload time')),
                ('description', models.TextField()),
                ('is_existed', models.BooleanField()),
                ('is_finish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='File name')),
                ('description', models.TextField(blank=True)),
                ('hash', models.CharField(max_length=100, verbose_name='MD5 hash of the file')),
                ('location', models.CharField(max_length=1024, verbose_name='Location of the file')),
                ('tags', models.JSONField(verbose_name='Tags of the file, which is an Array')),
                ('size', models.IntegerField(blank=True, verbose_name='Size of the file, by KiB')),
                ('time', models.DateTimeField(verbose_name='Time file uploaded')),
                ('storage_provider', models.CharField(blank=True, max_length=128, verbose_name='Provider of the storage: OSS/QiNiu')),
                ('storage_uri', models.CharField(blank=True, max_length=1024, verbose_name='URI of the file in given provider')),
                ('is_deleted', models.BooleanField(verbose_name='While file been deleted, the field is False')),
                ('is_folder', models.BooleanField(verbose_name='Whether this is a folder')),
                ('download_time_count', models.IntegerField()),
            ],
        ),
    ]
